bob = User.create!(username: "Bob", password:"12345")
jonny = User.create!(username: "Jonny", password:"12345")
billybob = User.create!(username: "Billybob", password:"12345")
jake = User.create!(username: "Jake", password:"12345")
maryjane = User.create!(username: "Mary Jane", password:"12345")
spiderman = User.create!(username: "Spiderman", password:"12345")

bobcats = Team.create!(name: "The Bobcats")
lighthouses = Team.create!(name: "The Lighthouses")
grizzlies = Team.create!(name: "The Grizzlies")
discovery = Team.create!(name: "Team Discovery Channel")
jaguars = Team.create!(name: "The Jaguars")

bob.pairings.create!(team: bobcats)
bob.pairings.create!(team: lighthouses)
bob.pairings.create!(team: grizzlies)
jonny.pairings.create!(team: bobcats)
billybob.pairings.create!(team: discovery)
billybob.pairings.create!(team: lighthouses)
jake.pairings.create!(team: jaguars)
maryjane.pairings.create!(team: jaguars)
spiderman.pairings.create!(team: grizzlies)
spiderman.pairings.create!(team: discovery)

today = List.create!(team_id: bobcats.id, user_id: bob.id, title: "To do today")
chores = List.create!(team_id: bobcats.id, user_id: bob.id, title: "Family chores")
project = List.create!(team_id: lighthouses.id, user_id: jonny.id, title: "Group project")
challenge = List.create!(team_id: lighthouses.id, user_id: jonny.id, title: "Team challenge")

today.tasks.create!(content: "Wash the dishes")
today.tasks.create!(content: "Do laundry")
chores.tasks.create!(content: "Eat hamburgers")
chores.tasks.create!(content: "Go to school")
project.tasks.create!(content: "Learn to code")
challenge.tasks.create!(content: "Eat")
today.tasks.create!(content: "Sleep")

